project:
  type: website

website:
  title: "Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: docs.qmd
        text: Docs
      - href: links.qmd
        text: Links

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



